### ISSUE TITLE
Diy kit container not selecting any vessel

### ISSUE THREAD

**Issue by anzroven19** [allista/GroundConstruction#27]
Greetings, i need some help regarding ground construction. Specifically diy kit containers,

When i am trying to select any vessel as blueprint, nothing happens. 

My ksp is 1.4.2 and the ground construction that i am using is the latest. 
I am also using kis and kas respectively, please help
![no vessel](https://user-images.githubusercontent.com/38457774/38904727-c1764ea0-42de-11e8-85af-2ff6198292fb.jpg)

**Comment by allista** [comment]
Latest GC is compiled against KSP-1.4.1, so it is probably an incompatibility. Try with 1.4.1, or wait for an update, please.

**Comment by BadOaks** [comment]
I had the same problem using the USI-MKS version (which is actually versioned for KSP 1.3.1). Replacing it with the latest GC release and copying the model/textures from the USI-MKS version fixed it for me.

**Comment by allista** [comment]
Oh, so USI still bundles the old version of GC dll then. I'll contact Bob about that.

**Comment by allista** [comment]
Realised the new version for KSP 1 4.3 yesterday, no issues there.
