### ISSUE TITLE
Kit Mass and Kit Res do not add up to vessel full mass

### ISSUE THREAD

**Issue by allista** [allista/GroundConstruction#28]
I know the topic of materials needed for construction of the DIY kits has been brought up before, but some extreme numbers has brought it to my attention lately. I wanted to construct a bsae on Duna, which is more unwieldy than it is heavy:

https://drive.google.com/open?id=1GqTlW6xh-Azz9A7jHqBROovWR01V4NGV

It is ~90 tons dry mass, with some machinery.

Now, if I put that into a DIY-kit, the mass ratio is sensible, as is the build cost for the kit itself from EL:

https://drive.google.com/open?id=1HkoJCv3G5o0pfFWDtD6jqaFVWEpo5E9B

Again, the masses add up and the Mkits and SP costs are reasonable. However, the kit reports it needs just above 700k of material kits to unpack! The mass difference should be around 40-50 tons in material kits, if you include the machinery already stored in the DIY kit.

**Comment by llinard** [comment]
The values I see in the second screenshot are:

Kit: Duna Base
Kit Mass: 64.4 t
**Kit Cost: 706,110.9 F**
Kit Work: 896.3 SKH
Kit Res.: 64,403.9 u

Correct me if I am wrong, but doesn't this show that the **_cost of the packed vessel_** inside the kit is **706,110.9 F** and not the cost to unpack/build the kit itself?

The base cost of the empty kit is **100 F** and the cost of the packed vessel is **706,110.9 F** for a total cost of **706,211 F**.  This perfectly matches the cost of the vessel as shown down in the bottom left corner of the screen.

I'm not seeing where it says that it requires 700k+ material kits to build it.

**Comment by allista** [comment]
You're correct, the cost is not the issue here; but the mass and kit res. are identical, which is clearly wrong. Anyway, I've fixed this yesterday.
And your additions to kit constraints were assigned released :)
