### ISSUE TITLE
Oversized deployed containers

### ISSUE THREAD

**Issue by fx-pain** [allista/GroundConstruction#43]
Got few vessels behaving like this:
![screenshot9](https://user-images.githubusercontent.com/33294916/46869206-0c07d680-ce3c-11e8-8cfa-1942a9dc0c50.png)
![screenshot10](https://user-images.githubusercontent.com/33294916/46869207-0ca06d00-ce3c-11e8-94bf-1ef2e45efe84.png)

This tends to happen with USI based vessels.
Nothing useful in logs.

[Z_miner_2.zip](https://github.com/allista/GroundConstruction/files/2473029/Z_miner_2.zip)

**Comment by allista** [comment]
That's because of the broken drill models. I've included most drills I could find in the blacklist, but hasn't released it yet. Try to grab the AT_Utils.glob file from the corresponding repo's development branch and see if it helps

**Comment by allista** [comment]
Here it is:
https://github.com/allista/AT_Utils/blob/development/GameData/000_AT_Utils/Plugins/PluginData/000_AT_Utils/000_AT_Utils.glob

**Comment by fx-pain** [comment]
Didn't help.
May be there were some related code changes also?

**Comment by allista** [comment]
Unfortunately, it wouldn't help with the existing containers, only with the new ones.

Ok, I'm planning to release during the weekend; although, your other bug seems more serious and less easy to fix (about heavy containers).

**Comment by fx-pain** [comment]
I tested it with newly created and assembled container on Duna in existing save. And with new save and container on Kerbin.

BTW "heavy container" also was unproportional by width (my bet - MSK habitation ring), but in space it's not really in issue.

**Comment by allista** [comment]
Fixed (and tested) this in AT_Utils. Will be in the next release.
