### ISSUE TITLE
No inflatable parts have workshop functionality, even when inflated

### ISSUE THREAD

**Issue by allista** [allista/GroundConstruction#5]
No inflatable parts have workshop functionality, even when inflated(old vessel, but the same vessel had workshop functionality on other parts)

Tundra assembly plant is only 50% workshop functionality.

I would expect the Ranger workshop and Tundra assembly plant to be around 100% as they are already workshops (although it may need to be a different configuration than making material kits or machinery, I did not check to see if that was an option).

The smallest 50% workshop I found was the tundra hub, so I will probably throw a couple of those on either my crew transport or the cargo hauler carrying the packaged base.(unless my final base package needs more than ~600 skill hours, at that point it makes sense to send up a ~250skh workshop rover kit as well)
 
I was kind of hoping I could use an inflatable workshop as my initial assembly facility(even if it was at 50%), might even design a base with a missing workshop so that I can then transfer it over after the base is built.

**Comment by allista** [comment]
@BobPalmer, there's two things we could do here:

1. You just explicitly add the GroundWorkshop module to these parts with Efficiency=watever_you_like
2. We establish a PartEvent communication between your inflatables and the GroundWorkshop, so that it could recalculate AutoEfficiency when the part changes size.

**Comment by BobPalmer** [comment]
I will be explicitly adding this function to a couple of specific modules :)
