### ISSUE TITLE
Ignore certain modules from the complexity calculation

### ISSUE THREAD

**Issue by lampeh** [allista/GroundConstruction#50]
It would be nice to have the option to ignore a list of part modules from the complexity calculation.

Some mods add modules to all parts that amount to basically just metadata, not functionality that would require additional SpecializedParts.

These are the stock part modules that I'd like to exclude:
- ModuleTestSubject
- ModulePartVariants
- FlagDecal
- ModuleOverheatDisplay

These are some modules added by mods that I'd like to exclude:
- KOSNameTag
- ModuleB9PropagateCopyEvents
- ModuleB9PartSwitch
- ModuleB9PartInfo
- ModuleConnectedLivingSpace
- ModuleKISItem     
- ModuleKISInventory (this one is rather special and would warrant handling of its own as it can contain other parts with resources)

I currently don't have a compiler for C# 6.0. I'll try to add some code to it when I get to update the development setup.

Thanks for this great mod! I already built bases, rovers and ships on Minmus with just a few resources shipped from Kerbin.

**Comment by allista** [comment]
Thanks for the suggestion. Sounds reasonable.
