### ISSUE TITLE
Ground Construction Core version mismatched in CKAN

### ISSUE THREAD

**Issue by brucelong** [allista/GroundConstruction#52]
The core mod, according to CKAN, has a different version than the the currently installed KSP version. (1.7.1)

**Comment by allista** [comment]
Not sure what you mean. Latest GC version was built against 1.7.0 but is compatible with the 1.7.1. And currently CKAN reports this correctly.

**Comment by brucelong** [comment]
![image](https://user-images.githubusercontent.com/6865485/60695594-233d9700-9e97-11e9-8ae2-ec989441addd.png)
When I attempt to install Ground Construction in 1.7.1 or 1.7.2

CKAN is marking the mod as incompatible. I can upload a screenshot. It might be my copy of CKAN, but other mods are working fine.

**Comment by allista** [comment]
I suspect it's not the GC-core, but the Community Resource Pack (on which it depends) that is marked for the older KSP version. The working would be to set supported KSP versions in CKAN settings manually.
