### ISSUE TITLE
Multiple workshops

### ISSUE THREAD

**Issue by Terwin1** [allista/GroundConstruction#6]
When multiple parts on one vessel are being used to construct a kit, each part needs to be individually associated with the kit in question and started.
Then once they are all activated they each calculate time remaining based only on the productivity of that one part and the work remaining.

Could there be a way to either combine multiple parts on a vessel into a larger 'virtual' workshop or to allow workshops to recognize that a given kit is being worked on by other workshops?

**Comment by allista** [comment]
I **will do the latter** and will think about the former.
Virtual workshop is a nice concept, but I have no idea how to implement it yet...

**Comment by allista** [comment]
**Virtual workshop**: implemented as a VesselModule; allows (through the main GC window) to sync the kit under construction between all the workshops of a vessel. Not the same as a true virtual workshop (with single queue and so on), but serves the purpose with minimal effort and additional UI clutter.
https://github.com/allista/GroundConstruction/blob/development/WorkshopManager.cs
 
**ETA computation during concurrent construction**: implementation still has some flaws which I need to solve.
