### ISSUE TITLE
Paying loaded price for empty containers?

### ISSUE THREAD

**Issue by Terwin1** [allista/GroundConstruction#7]
When designing a vessel to be constructed by GC, emptying containers of expensive resources(I have tested Enriched Uranium, Rare Metals and Exoitc Minerals), the price of the kit generated from the saved vessel does not reflect that the storage was emptied.

In one example, the only difference between the kits for a probe core+empty EU pod and probe core+full EU pod was the weight and number of material kits required, the cost of the kit was the same.

In another example, a MKS cargo module was set to Commodities(Rare metals and exotic minerals), and the cost of the kit was roughly the same as if the cargo module was full, then when I repainted it to dirt, the cost of the kit generated was much less(both cargo modules were empty)

This seems like a pricing error.

**Comment by allista** [comment]
Could you please test this fix and tell me if it works as you expect it to?
https://github.com/allista/GroundConstruction/releases/download/v1.1.2/GroundConstruction-1.1.2.0.zip

**Comment by Terwin1** [comment]
It looks like it is now using the empty price and weight for all containers except for enriched uranium, and for that one it looks like it is keeping the amount of the resource that was loaded and reflecting that as increased cost and weight for the kit(then adding it to the constructed vessel).

I would consider that a very reasonable approach that should cover the needs for MKS.

Looking at KitResources.cfg it looks like you are also covering heat shields, solid rockets, and several other nuclear fuels the same way.  This should also make it easily configurable for any other resources that users would prefer to stay in place.

Looks good and I cannot think of any further improvements for this element of the cost calculations.

**Comment by allista** [comment]
Thanks for the tests and analysis!
I will publish it as is then, and will tend to other issues later.
