### ISSUE TITLE
Space crane lights illuminate planets

### ISSUE THREAD

**Issue by lampeh** [allista/GroundConstruction#74]
The space crane lights up the planet from space.

Possibly related to this post:
"The solution to this problem is to set the culling mask of the light to ignore the 10.th layer (Scaled Scenery)" ( https://forum.kerbalspaceprogram.com/index.php?/topic/157390-solved-spotlights-illuminating-planets-from-space/ )

![Kerbal Space Program 21 05 2020 00_49_38](https://user-images.githubusercontent.com/758097/82505937-c5da2500-9afe-11ea-8c4d-f623c8d3e275.jpg)

**Comment by Kerbas-ad-astra** [comment]
Taniwha's [lightfix.py](https://github.com/taniwha/io_object_mu/blob/master/lightfix.py) can be used to fix the model(s) in question without even opening them in an editor.

**Comment by allista** [comment]
@Kerbas-ad-astra wow, thanks!

**Comment by lampeh** [comment]
```
$ python3 ./lightfix.py SpaceCrane-tank.mu 
checking SpaceCrane-tank.mu fixed
```

It does, indeed!. Thanks!
