### ISSUE TITLE
Workshops don't realize they have engineers.

### ISSUE THREAD

**Issue by DanStaal** [allista/GroundConstruction#8]
Workshops seem to only check to see if they have an engineer at physics load, not at construction start.  This makes moving an engineer into a workshop a bit awkward, as you have to leave the scene and come back before changes take effect.

**Comment by allista** [comment]
Rechecked it just now, using both EVA transfers and direct transfers from part to part. Both works as expected.

**Comment by allista** [comment]
This should be "fixed" as engineers with 0 experience now also capable of construction.
